accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('user_exists/', views.user_exists, name='user_exists'),
    path('userid_exists/', views.userid_exists, name='userid_exists'),
    path('', views.signin, name="home")
]

hello/urls.py
from django.urls import path, include
from . import views

app_name = 'projecttime'
urlpatterns = [
    path('projects', views.get_projects, name="get_projects"),
    path('entries', views.get_entries, name='get_entries'),
    path('submit_entries', views.submit_entries, name='submit_entries'),
    path('', views.index, name="index"),
    path('test', views.test, name="test"),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hello.urls')), # index url
    path('projecttime/', include('hello.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    myid = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return "{} ({})".format(self.user.username, self.myid)

hello/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Project(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

class ProjectTimeEntry(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    hour = models.FloatField('project hour', validators=(MinValueValidator(0.5), MaxValueValidator(24))) 
    date = models.DateField('date')

    def __str__(self):
        return '{}@{} on {}: {}'.format(self.user, self.project, self.date, self.hour)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import Http404
from django.contrib.auth.models import User
from accounts.models import Profile
from django.http import HttpResponse
import json

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

def user_exists(request):
    user_exist = True
    username = request.GET['username']
    try:
        User.objects.get(username=username)
        user_exist = True
    except User.DoesNotExist:
        user_exist = False

    return HttpResponse(json.dumps(user_exist))

def userid_exists(request):
    exists = True
    userid = request.GET['userid']
    try:
        Profile.objects.get(myid=userid)
        exists = True
    except Profile.DoesNotExist:
        exists = False

    return HttpResponse(json.dumps(exists))

def signup(request):
    if request.method == 'GET':
        return render(request, 'accounts/signup.html', {})

    elif request.method == 'POST':
        user = User.objects.create_user(
            username=request.POST['username'],
            password=request.POST['password'])

        profile = Profile()
        profile.user = user
        profile.myid = request.POST['userid']
        profile.save()

        return redirect("accounts:login")
    else:
        raise Http404("method does not exist for sign in")
    
    
def signin(request):
    if request.method == 'GET':
        return render(request, 'accounts/signin.html', {})

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/projecttime/')
        else:
            print("invalid signin")
            return render(request, 'accounts/signin.html', {"signin_error":True})

    else:
        raise Http404("method does not exist for sign in")


def signout(request):
    logout(request)

    return redirect("accounts:login")

hello/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.template import loader
from .models import ProjectTimeEntry, Project
from django.contrib.auth.models import User
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json
import logging
from django.contrib.auth.decorators import login_required

logger = logging.getLogger(__name__)

@login_required
def index(request):
    if request.user.profile is None:
        raise Http404("invalid user login")

    # booststrap style
    return render(request, 'projecttime/report_table_bs.html',
                  {'user_name': request.user.username,
                   'user_id': request.user.profile.myid})

def get_projects(request):
    projects = [project.name for project in Project.objects.all()]
    data = json.dumps(projects)
    print(data) 
    return HttpResponse(data)

def get_entries(request):
    records = ProjectTimeEntry.objects.filter(user__profile__myid=request.GET['user'],
                                              date__gte=request.GET['from'],
                                              date__lte=request.GET['to'])

    entries = [{'user': r.user.username,
                'project': r.project.name,
                'date': r.date.isoformat(),
                'hour': r.hour} for r in records]
    
    data = json.dumps(entries)
    print(entries)
    return HttpResponse(data)
    
@csrf_exempt
def submit_entries(request):
    entries=json.loads(request.body)
    
    #FIXME: there is flaw that if the new entries are invalid, e.g, invalid project,
    # the existing entries will be removed and no entries added to datebase
    #
    # We should make sure  the existing entries are not deleted until all 
    # the new entries are valid to be added to database
    for entry in entries:
        ProjectTimeEntry.objects.filter(date=entry["date"]).delete()

    # add new entries
    for entry in entries:
        print(entry)
        e = ProjectTimeEntry()
        e.project = Project.objects.get(name=entry['project'])
        e.user = User.objects.get(profile__myid=entry['user'])
        e.date =  datetime.datetime.strptime(entry['date'], "%Y-%m-%d").date()

        hour = 0
        try:
            hour = int(entry['hour'])
        except ValueError:
            logger.error('invalid hour format')

        if hour > 0:
            e.hour = hour
            e.save()

    return HttpResponse("OK")


#################
# Test function #
#################
def test(request):
    return render(request, 'projecttime/test.html', {})

accounts/templates/accounts/signin.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Sign In</title>

  {% load static %}
  <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap/4.1.3/css/bootstrap.min.css' %}">

  <style type="text/css">
    .login-form {
      width: 340px;
      margin: 50px auto;
    }

    .login-form form {
      margin-bottom: 15px;
      background: #f7f7f7;
      box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
      padding: 30px;
    }
  </style>

</head>

<body class="text-center">
  <div class="login-form">
    <form method="POST">
      {% csrf_token %}
      <h1 class="h3 mb-3 font-weight-normal">Sign in</h1>
    {% if signin_error %}
      <p class="text-danger">
        Your username and password didn't match. Please try again.
      </p>
    {% endif %}
      <input type="text" id="userName" class="form-control" placeholder="Name" name="username" required autofocus>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
    <a href="{% url 'accounts:signup' %}">Register</a>

  </div>
</body>

</html>

accounts/templates/accounts/signup.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Sign Up</title>

  {% load static %}
  <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap/4.1.3/css/bootstrap.min.css' %}">

  <style type="text/css">
    .login-form {
      width: 340px;
      margin: 50px auto;
    }

    .login-form form {
      margin-bottom: 15px;
      background: #f7f7f7;
      box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
      padding: 30px;
    }
  </style>

  <script>
    /**
     * set field validity for custom validation. It extracts
     * the error text from the sibling of the given element to
     * show to user
     * @param  element      html element to be set
     * @param  validity     validity to be set
     */
    function setValidity(element, validity) {
      if (validity) {
        element[0].setCustomValidity("");
      }
      else {
        var errMsg = element.siblings(".invalid-feedback").text()
        element[0].setCustomValidity(errMsg);
      }

      // element[0].reportValidity();
    }

    $(document).ready(function () {
      function checkUserExists(userName, handler) {
        $.get("/accounts/user_exists", { "username": userName },
          function (response, status) {
            var userExists = JSON.parse(response);
            handler(userExists);
          });
      }

      $('#username').focusout(function () {
        var input = $(this);
        checkUserExists(input.val(), function (isExists) {
          var isValid = !isExists;
          setValidity(input, isValid);
        });
      });

      function checkUserIDExists(userID, handler) {
        $.get("/accounts/userid_exists", { "userid": userID },
          function (data, status) {
            var exists = JSON.parse(data)
            handler(exists);
          });
      }

      $("#userid").focusout(function () {
        var input = $(this);
        checkUserIDExists($(this).val(), function (isExists) {
          var isValid = !isExists;
          setValidity(input, isValid);
        });
      });

    });

  </script>
</head>

<body>
  <div class="login-form">
    <form method="POST">
      {% csrf_token %}
      <h1 class="mb-3 text-center">Register</h1>

      <form-group>
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" placeholder="Name" name="username" required autofocus>
        <div class="invalid-feedback">
          Please use different name, as it's already taken.
        </div>
      </form-group>

      <form-group>
        <label class="text-left" for="userid">User ID</label>
        <input type="text" class="form-control" id="userid" placeholder="ID" name="userid" required autofocus>
        <div class="invalid-feedback">
          Please use different ID, as it's already taken.
        </div>
      </form-group>

      <form-group>
        <label class="" for="password"> Password </label>
        <input type="password" class="form-control" id="password" placeholder="Password" name="password" required>
        <small id="passwordHelpBlock" class="form-text text-muted">
          Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special
          characters, or emoji.
        </small>
      </form-group>

      <button class="btn btn-lg btn-primary btn-block mt-3" type="submit">Register</button>
    </form>
    <a class="text-center" href="{% url 'accounts:login' %}">Login</a>
  </div>
</body>

</html>

hello/templates/projecttime/datatable.html
<html>

<head>
    <title>This is a playground jquery plugin datatable</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

    <script>
        var dataSet = [
            ["Tiger Nixon", "System Architect", "Edinburgh", "5421", "2011/04/25", "$320,800"],
            ["Garrett Winters", "Accountant", "Tokyo", "8422", "2011/07/25", "$170,750"],
            ["Ashton Cox", "Junior Technical Author", "San Francisco", "1562", "2009/01/12", "$86,000"],
            ["Cedric Kelly", "Senior Javascript Developer", "Edinburgh", "6224", "2012/03/29", "$433,060"],
            ["Airi Satou", "Accountant", "Tokyo", "5407", "2008/11/28", "$162,700"],
            ["Brielle Williamson", "Integration Specialist", "New York", "4804", "2012/12/02", "$372,000"],
            ["Herrod Chandler", "Sales Assistant", "San Francisco", "9608", "2012/08/06", "$137,500"],
            ["Rhona Davidson", "Integration Specialist", "Tokyo", "6200", "2010/10/14", "$327,900"],
            ["Colleen Hurst", "Javascript Developer", "San Francisco", "2360", "2009/09/15", "$205,500"],
            ["Sonya Frost", "Software Engineer", "Edinburgh", "1667", "2008/12/13", "$103,600"],
            ["Jena Gaines", "Office Manager", "London", "3814", "2008/12/19", "$90,560"],
            ["Quinn Flynn", "Support Lead", "Edinburgh", "9497", "2013/03/03", "$342,000"],
            ["Charde Marshall", "Regional Director", "San Francisco", "6741", "2008/10/16", "$470,600"],
            ["Haley Kennedy", "Senior Marketing Designer", "London", "3597", "2012/12/18", "$313,500"],
            ["Tatyana Fitzpatrick", "Regional Director", "London", "1965", "2010/03/17", "$385,750"],
            ["Michael Silva", "Marketing Designer", "London", "1581", "2012/11/27", "$198,500"],
            ["Paul Byrd", "Chief Financial Officer (CFO)", "New York", "3059", "2010/06/09", "$725,000"],
            ["Gloria Little", "Systems Administrator", "New York", "1721", "2009/04/10", "$237,500"],
            ["Bradley Greer", "Software Engineer", "London", "2558", "2012/10/13", "$132,000"],
            ["Dai Rios", "Personnel Lead", "Edinburgh", "2290", "2012/09/26", "$217,500"],
            ["Jenette Caldwell", "Development Lead", "New York", "1937", "2011/09/03", "$345,000"],
            ["Yuri Berry", "Chief Marketing Officer (CMO)", "New York", "6154", "2009/06/25", "$675,000"],
            ["Caesar Vance", "Pre-Sales Support", "New York", "8330", "2011/12/12", "$106,450"],
            ["Doris Wilder", "Sales Assistant", "Sidney", "3023", "2010/09/20", "$85,600"],
            ["Angelica Ramos", "Chief Executive Officer (CEO)", "London", "5797", "2009/10/09", "$1,200,000"],
            ["Gavin Joyce", "Developer", "Edinburgh", "8822", "2010/12/22", "$92,575"],
            ["Jennifer Chang", "Regional Director", "Singapore", "9239", "2010/11/14", "$357,650"],
            ["Brenden Wagner", "Software Engineer", "San Francisco", "1314", "2011/06/07", "$206,850"],
            ["Fiona Green", "Chief Operating Officer (COO)", "San Francisco", "2947", "2010/03/11", "$850,000"],
            ["Shou Itou", "Regional Marketing", "Tokyo", "8899", "2011/08/14", "$163,000"],
            ["Michelle House", "Integration Specialist", "Sidney", "2769", "2011/06/02", "$95,400"],
            ["Suki Burks", "Developer", "London", "6832", "2009/10/22", "$114,500"],
            ["Prescott Bartlett", "Technical Author", "London", "3606", "2011/05/07", "$145,000"],
            ["Gavin Cortez", "Team Leader", "San Francisco", "2860", "2008/10/26", "$235,500"],
            ["Martena Mccray", "Post-Sales support", "Edinburgh", "8240", "2011/03/09", "$324,050"],
            ["Unity Butler", "Marketing Designer", "San Francisco", "5384", "2009/12/09", "$85,675"]
        ];

        $(document).ready(function () {
            $('#example').DataTable({
                data: dataSet,
                columns: [
                    { title: "Name" },
                    { title: "Position" },
                    { title: "Office" },
                    { title: "Extn." },
                    { title: "Start date" },
                    { title: "Salary" }
                ]
            });
        });
    </script>
</head>

<body>
    <table id="example" class="display" width="100%"></table>
</body>
</html>

hello/templates/projecttime/report_table_bs.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'projecttime/date_util.js' %}"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/4.1.3/css/bootstrap.min.css' %}">
    
    <!-- hide spin box in number input  -->
    <style>
        input[type='number'] {
        -moz-appearance:textfield;
        }

        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
        }
    </style>

    <script>
        function getWeeklyReportFrom(entries) {
            // report uses project as key and uses an array with size 7 as value. 
            // This array represents hours spent from Monday to Sunday
            var report = {}
            for (var i = 0; i < entries.length; ++i) {
                var entry = entries[i];

                if (!(entry.project in report)) {
                    // create default hour list for new project
                    report[entry.project] = [0, 0, 0, 0, 0, 0, 0]
                }

                var date = new Date(entry.date);
                report[entry.project][ISOWeekDay(date)] += entry.hour;
            }
            return report;
        }

        function createProjectSelect() {
            var select = $("<select/>").addClass("custom-select");
            for (var project of window["projects"]) {
                select.append($("<option/>").val(project).text(project));
            }
            return select;
        }

        function fillReportTable(report) {
            var report_table = $("#report_table");
            report_table.children("tbody").remove();

            var body = $("<tbody/>")
            for (var project in report) {
                body.append(
                    $("<tr/>").append(
                        $("<td/>").append(createProjectSelect().val(project)),
                        $("<td/>").append(createHourInput().val(report[project][0])),
                        $("<td/>").append(createHourInput().val(report[project][1])),
                        $("<td/>").append(createHourInput().val(report[project][2])),
                        $("<td/>").append(createHourInput().val(report[project][3])),
                        $("<td/>").append(createHourInput().val(report[project][4])),
                        $("<td/>").append(createHourInput().val(report[project][5])),
                        $("<td/>").append(createHourInput().val(report[project][6]))));
            }

            body.append(createReportTableEmptyRow());
            report_table.append(body)
        }

        function populateWeekNumberSelect(maxWeek) {
            var year = (new Date()).getFullYear();
            for (var week = 1; week <= maxWeek; ++week) {
                var opText =  week + " @ " + shortString(getDateOfISOWeek(week, year));
                $("#week_number").append($("<option />").val(week).text(opText));
            }
        }

        function requestAndLoadEntries(user, from, to) {
            console.log("GET entries...")

            $.get("entries",
                { "user": user, "from": from, "to": to },
                function (data, status) {
                    console.log("GET entries: " + data)
                    var entries = JSON.parse(data);
                    var report = getWeeklyReportFrom(entries);
                    fillReportTable(report);
                });
        }

        function postEntries(entries, success, fail) {
            console.log("POST submit_entries ... params: " + JSON.stringify(entries))
            $.ajax({
                type: 'post',
                url: 'submit_entries',
                data: JSON.stringify(entries),
                contentType: "application/json; charset=utf-8",
                traditional: true,
                success: success
            }).fail(fail);
        }

        function extractTableData() {
            var tblData = []
            $("#report_table tbody tr").each(function (row, tr) {
                var row = $(tr).find("td").map(function (idx, td) {
                    return $(td).children().val();
                }).get();

                tblData.push(row);
            });

            return tblData;
        }

        function getEntriesFromTable() {
            var tableData = extractTableData();

            var entries = [];
            var currentYear = (new Date()).getFullYear();
            var week = $("#week_number").val();
            var fromDate = getDateOfISOWeek(week, currentYear);
            var user = $("#user_id").val();
            for (var row of tableData) {
                entries.push({ "user": user, "project": row[0], "date": shortString(plusDay(fromDate, 0)), "hour": row[1] });
                entries.push({ "user": user, "project": row[0], "date": shortString(plusDay(fromDate, 1)), "hour": row[2] });
                entries.push({ "user": user, "project": row[0], "date": shortString(plusDay(fromDate, 2)), "hour": row[3] });
                entries.push({ "user": user, "project": row[0], "date": shortString(plusDay(fromDate, 3)), "hour": row[4] });
                entries.push({ "user": user, "project": row[0], "date": shortString(plusDay(fromDate, 4)), "hour": row[5] });
                entries.push({ "user": user, "project": row[0], "date": shortString(plusDay(fromDate, 5)), "hour": row[6] });
                entries.push({ "user": user, "project": row[0], "date": shortString(plusDay(fromDate, 6)), "hour": row[7] });
            }

            return entries;
        }

        function initWeekNumberSelect() {
            var now = new Date();
            var currentWeek = getISOWeek(now);
            populateWeekNumberSelect(currentWeek);

            // attach #week_number "change" event handler which request entries from server
            $("#week_number").change(function () {
                var week = $(this).val()
                var from = getDateOfISOWeek(week, now.getFullYear())
                var to = new Date(from.getTime());
                to.setDate(to.getDate() + 6);

                // update date in the heading of report table
                $("#report_table thead").find(".thead-date").each(function (idx, td) {
                    $(td).text(shortString(plusDay(from, idx)));
                })
                
                // request entries from server
                requestAndLoadEntries($("#user_id").val(), shortString(from), shortString(to));
            });

            // select current week and trigger "change" event
            $("#week_number").val(currentWeek).change();
        }

        function initMoreEntry() {
            $("#more_entry").click(function (event) {
                event.preventDefault();
                $("#report_table tbody").append(createReportTableEmptyRow());
            });
        }
        
        function createHourInput()
        {
            return $("<input/>").addClass("form-control")
                                .attr("type", "number")
                                .attr("min", 0)
                                .attr("max", 24)
                                .attr("step", 0.1);
        }

        function createReportTableEmptyRow() {
            var row = $("<tr/>").append(
                $("<td/>").append(createProjectSelect()),
                $("<td/>").append(createHourInput()),
                $("<td/>").append(createHourInput()),
                $("<td/>").append(createHourInput()),
                $("<td/>").append(createHourInput()),
                $("<td/>").append(createHourInput()),
                $("<td/>").append(createHourInput()),
                $("<td/>").append(createHourInput()));

            return row;
        }

        function initSubmitButton() {
            $("#submit").click(function () {
                var entries = getEntriesFromTable();
                postEntries(entries, 
                /*success*/ function () {
                                indicateSubmitStatus(true)
                                // simulate user selects week number to refetch data from server
                                $("#week_number").change();
                            },
                   /*fail*/ function()
                            {
                                indicateSubmitStatus(false);
                            });
            });
        }

        function indicateSubmitStatus(success)
        {
            console.log("indicate submit status:" + success);
            var style = "";
            var message = ""
            if (success)
            {
                style = "alert-success";
                message = "submit succeed";
               
            }
            else
            {
                style = "alert-danger";
                message = "submit failed";
            }

            // apply alter style
            $("#submit_result").addClass(style).text(message).show().delay(1000).fadeOut(
                "fast", 
                function()
                {
                    // remove alter style after hidden
                    $("#submit_result").removeClass(style).text("");
                });
        }

        function getProjectList() {
            // WORKAROUND: use synchronous call to get project list from server. 
            // This will fix the issue that project isn't shown on report table. 
            // This is because the response for GET-entries might arrive earlier than GET-projects
            // even though GET-projects request is issued firstly. In this case, the report table 
            // will be filled while the project list is not available yet.
            console.log("GET projects synchronously...")
            $.ajax({
                type: 'GET',
                url: 'projects',
                async: false,
                success: function (data) {
                    console.log("GET projects: " + data)
                    window['projects'] = JSON.parse(data)
                }
            });
        }

        $(document).ready(function () {
            getProjectList();
            initWeekNumberSelect();
            initSubmitButton();
            initMoreEntry();
        });
    </script>

    <title> Weekly Report</title>
</head>

<body>
    <div class="container">
        <div class="d-flex justify-content-center">
                <h2 class="text-right"> Hello, {{ user_name }} 
                </h2>
                <div class="align-self-end">
                    <p ><a href="{% url 'accounts:logout' %}" class="badge badge-pill badge-primary align-self-end">logout</a></p>
                </div>
                
        </div>
        
        <input type="hidden" id="user_id" value="{{user_id}}">

        <div class="table-wrapper clearfix">
            <div class="table-filter d-flex float-left">
                <label class="input-group-text" for="week_number">Week</label>
                <select class="custom-select" id="week_number"> </select>
            </div>

            <div class="table-action d-flex float-right">
                <button type="button" class="btn btn-info" id="more_entry">Add New</button>
                <button type="button" class="btn btn-primary" id="submit">Submit</button>
            </div>

        </div>
        
        <br>
        <table class="table table-striped table-sm" id="report_table">
            <thead>
                <tr>
                    <th scope="col"> Project </th>
                    <th scope="col"> Mon. <small class="thead-date"></small> </th>
                    <th scope="col"> Tue. <small class="thead-date"></small> </th>
                    <th scope="col"> Wed. <small class="thead-date"></small> </th>
                    <th scope="col"> Thu. <small class="thead-date"></small> </th>
                    <th scope="col"> Fri. <small class="thead-date"></small> </th>
                    <th scope="col"> Sat. <small class="thead-date"></small> </th>
                    <th scope="col"> Sun. <small class="thead-date"></small> </th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

        <div id="submit_result" class="alert" role="alert">
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'popper/1.14.6/popper.js' %}"></script>
    <script src="{% static 'bootstrap/4.1.3/js/bootstrap.min.js' %}"></script>
</body>

</html>

hello/templates/projecttime/user.html
{% if user_list %}
    <ul>
        {% for u in user_list %}
            <li><a href="{% url 'projecttime:user_name' u.name %}">{{u.name}}</a> </li>
        {% endfor %}
    </ul>
{% else %}
    <p> no user added </p>
{% endif %}

hello/templates/projecttime/users.html
{% if user_list %}
    <ul>
        {% for u in user_list %}
            <li><a href="{% url 'projecttime:report' u.user_id %}">{{u.name}}</a> </li>
        {% endfor %}
    </ul>
{% else %}
    <p> no user added </p>
{% endif %}

hello/templates/user/index.html
{% if user_list %}
    <ul>
        {% for u in user_list %}
            <li><a href="/user/{{u.name}}">{{u.name}}</a> </li>
        {% endfor %}
    </ul>
{% else %}
    <p> no user added </p>
{% endif %}

hello/templates/user/project_time.html
{% if project_time_list %}
    {% for pt in project_time_list %}
        <ur>
            <li>
                {{pt.user}} @ {{pt.project}} on {{pt.date}}
            </li>
        </ur>
    {% endfor %}
{% else %}
<p> no project time available</p>
{% endif %}

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>